// Barangays of Tagum City, Davao del Norte.
// Please double-check this list against your local records before going live.
export const TAGUM_BARANGAYS = [
  "Apokon",
  "Bincungan",
  "Busaon",
  "Canocotan",
  "Cuambogan",
  "La Filipina",
  "Liboganon",
  "Madaum",
  "Magdum",
  "Magugpo East",
  "Magugpo North",
  "Magugpo Poblacion",
  "Magugpo South",
  "Magugpo West",
  "Mankilam",
  "New Balamban",
  "Nueva Fuerza",
  "Pagsabangan",
  "Pandapan",
  "San Agustin",
  "San Isidro",
  "San Miguel",
  "Visayan Village",
];
